# Generated by Django 5.1.3 on 2024-12-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cliente_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='avaliacao',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produto'),
        ),
    ]
